-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20261005075054_AddAccessRequests
-- One row per account waiting for approval, so the administrator is notified once (Telegram).
-- Email and Name are encrypted by the API ("enc1:..."), hence text.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

CREATE TABLE IF NOT EXISTS "AccessRequests" (
    "Id"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "Email"      text         NULL,
    "Name"       text         NULL,
    "NotifiedAt" timestamp with time zone NULL,
    "CreatedAt"  timestamp with time zone NOT NULL,
    "UpdatedAt"  timestamp with time zone NULL,
    "OwnerId"    varchar(255) NOT NULL,
    CONSTRAINT "PK_AccessRequests" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AccessRequests_OwnerId"
    ON "AccessRequests" ("OwnerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261005075054_AddAccessRequests', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
