-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20261003094352_AddEInvoicing
-- Structured e-invoices (Facturae...): the extra data country regimes ask for on each customer,
-- the user's encrypted signing certificate, and the e-invoice file generated for each invoice.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "ComplianceValues" text NOT NULL DEFAULT '{}';

ALTER TABLE "ComplianceSettings" ADD COLUMN IF NOT EXISTS "CertificateNotAfter"          timestamp with time zone NULL;
ALTER TABLE "ComplianceSettings" ADD COLUMN IF NOT EXISTS "CertificateSubject"           varchar(500)  NULL;
ALTER TABLE "ComplianceSettings" ADD COLUMN IF NOT EXISTS "CertificateThumbprint"        varchar(100)  NULL;
ALTER TABLE "ComplianceSettings" ADD COLUMN IF NOT EXISTS "ProtectedCertificate"         text          NULL;
ALTER TABLE "ComplianceSettings" ADD COLUMN IF NOT EXISTS "ProtectedCertificatePassword" varchar(4000) NULL;

CREATE TABLE IF NOT EXISTS "InvoiceEInvoices" (
    "Id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId"     bigint       NOT NULL,
    "CountryCode"   varchar(2)   NOT NULL,
    "FormatId"      varchar(50)  NOT NULL,
    "Content"       bytea        NOT NULL,
    "ContentType"   varchar(100) NOT NULL,
    "FileExtension" varchar(10)  NOT NULL,
    "Sha256"        varchar(64)  NOT NULL,
    "GeneratedAt"   timestamp with time zone NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "UpdatedAt"     timestamp with time zone NULL,
    "OwnerId"       varchar(255) NOT NULL,
    CONSTRAINT "PK_InvoiceEInvoices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceEInvoices_Invoices_InvoiceId"
        FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_InvoiceEInvoices_InvoiceId_FormatId"
    ON "InvoiceEInvoices" ("InvoiceId", "FormatId");

CREATE INDEX IF NOT EXISTS "IX_InvoiceEInvoices_OwnerId"
    ON "InvoiceEInvoices" ("OwnerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261003094352_AddEInvoicing', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
