-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20260925081905_AddInvoiceEmails
-- Invoice emails as Gmail drafts: customer recipients, per-customer email templates,
-- the user's Gmail authorization, pending OAuth states and the log of created drafts.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "Email"    varchar(320)  NULL;
ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "CcEmails" varchar(1000) NULL;

CREATE TABLE IF NOT EXISTS "EmailTemplates" (
    "Id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint       NOT NULL,
    "Name"       varchar(200) NOT NULL,
    "Subject"    varchar(500) NOT NULL,
    "Body"       text         NOT NULL,
    "IsActive"   boolean      NOT NULL,
    "CreatedAt"  timestamp with time zone NOT NULL,
    "UpdatedAt"  timestamp with time zone NULL,
    CONSTRAINT "FK_EmailTemplates_Customers_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_EmailTemplates_CustomerId"
    ON "EmailTemplates" ("CustomerId");

CREATE TABLE IF NOT EXISTS "GmailConnections" (
    "Id"                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"                varchar(200)  NOT NULL,
    "EmailAddress"          varchar(320)  NOT NULL,
    "EncryptedRefreshToken" varchar(4000) NOT NULL,
    "Scopes"                varchar(1000) NOT NULL,
    "ConnectedAt"           timestamp with time zone NOT NULL,
    "LastUsedAt"            timestamp with time zone NULL,
    "CreatedAt"             timestamp with time zone NOT NULL,
    "UpdatedAt"             timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GmailConnections_UserId"
    ON "GmailConnections" ("UserId");

CREATE TABLE IF NOT EXISTS "OAuthStates" (
    "Id"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "State"     varchar(100) NOT NULL,
    "UserId"    varchar(200) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_OAuthStates_State"
    ON "OAuthStates" ("State");

CREATE TABLE IF NOT EXISTS "InvoiceEmails" (
    "Id"             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InvoiceId"      bigint        NOT NULL,
    "From"           varchar(320)  NOT NULL,
    "To"             varchar(2000) NOT NULL,
    "Cc"             varchar(2000) NULL,
    "Subject"        varchar(1000) NOT NULL,
    "Attachments"    varchar(2000) NOT NULL,
    "GmailDraftId"   varchar(200)  NOT NULL,
    "GmailMessageId" varchar(200)  NOT NULL,
    "RfcMessageId"   varchar(500)  NOT NULL,
    "CreatedAt"      timestamp with time zone NOT NULL,
    "UpdatedAt"      timestamp with time zone NULL,
    CONSTRAINT "FK_InvoiceEmails_Invoices_InvoiceId"
        FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_InvoiceEmails_InvoiceId"
    ON "InvoiceEmails" ("InvoiceId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260925081905_AddInvoiceEmails', '10.0.9')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
