-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20260925102916_AddHolidayCalendars
-- Public holiday calendars per country (editable rules, created from the built-in ones on
-- first use by the app) and the customer's holiday country.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

ALTER TABLE "Customers" ADD COLUMN IF NOT EXISTS "HolidayCountry" varchar(2) NULL;

CREATE TABLE IF NOT EXISTS "HolidayCalendars" (
    "Id"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CountryCode" varchar(2) NOT NULL,
    "CreatedAt"   timestamp with time zone NOT NULL,
    "UpdatedAt"   timestamp with time zone NULL
);

-- One calendar per country. Once 20260926_add-owner-id has run the rule is per user and this
-- index no longer exists; recreating it on a re-run would fail (or wrongly forbid two users
-- having a calendar for the same country), so it is only created before "OwnerId" exists.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'HolidayCalendars' AND column_name = 'OwnerId') THEN
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_HolidayCalendars_CountryCode"
            ON "HolidayCalendars" ("CountryCode");
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HolidayRules" (
    "Id"                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "HolidayCalendarId" bigint       NOT NULL,
    "Name"              varchar(200) NOT NULL,
    "Kind"              varchar(20)  NOT NULL,
    "Month"             integer      NULL,
    "Day"               integer      NULL,
    "EasterOffset"      integer      NULL,
    "Weekday"           varchar(10)  NULL,
    "Occurrence"        integer      NULL,
    "FromYear"          integer      NULL,
    "ToYear"            integer      NULL,
    "IsActive"          boolean      NOT NULL,
    "CreatedAt"         timestamp with time zone NOT NULL,
    "UpdatedAt"         timestamp with time zone NULL,
    CONSTRAINT "FK_HolidayRules_HolidayCalendars_HolidayCalendarId"
        FOREIGN KEY ("HolidayCalendarId") REFERENCES "HolidayCalendars" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_HolidayRules_HolidayCalendarId"
    ON "HolidayRules" ("HolidayCalendarId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260925102916_AddHolidayCalendars', '10.0.9')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
