-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20261003143323_AddEInvoiceSubmissions
-- Where the e-invoice of an invoice was delivered (Spain: FACe) and where it stands there. A row exists only
-- once the channel accepted the file; the file it refers to cannot be deleted while the row exists.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

CREATE TABLE IF NOT EXISTS "EInvoiceSubmissions" (
    "Id"                 bigint GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceEInvoiceId"  bigint        NOT NULL,
    "ChannelId"          varchar(50)   NOT NULL,
    "Environment"        varchar(20)   NOT NULL,
    "Reference"          varchar(100)  NOT NULL,
    "SubmittedAt"        timestamp with time zone NOT NULL,
    "RegisteredAt"       timestamp with time zone NULL,
    "StatusCode"         varchar(20)   NULL,
    "StatusName"         varchar(200)  NULL,
    "CancellationStatus" varchar(200)  NULL,
    "CheckedAt"          timestamp with time zone NULL,
    "LastError"          varchar(1600) NULL,
    "CreatedAt"          timestamp with time zone NOT NULL,
    "UpdatedAt"          timestamp with time zone NULL,
    "OwnerId"            varchar(255)  NOT NULL,
    CONSTRAINT "PK_EInvoiceSubmissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EInvoiceSubmissions_InvoiceEInvoices_InvoiceEInvoiceId"
        FOREIGN KEY ("InvoiceEInvoiceId") REFERENCES "InvoiceEInvoices" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_EInvoiceSubmissions_InvoiceEInvoiceId_ChannelId"
    ON "EInvoiceSubmissions" ("InvoiceEInvoiceId", "ChannelId");

CREATE INDEX IF NOT EXISTS "IX_EInvoiceSubmissions_OwnerId"
    ON "EInvoiceSubmissions" ("OwnerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261003143323_AddEInvoiceSubmissions', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
