-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20260906182657_AddProjectsAndWorkDayProjects
-- Adds per-customer Projects and per-work-day project time allocations.
-- Idempotent: safe to run repeatedly.
--
-- Assumes the "Customers" and "WorkDays" tables already exist with a numeric
-- primary key "Id" (SERIAL/int or bigint - a bigint FK is comparable to either).

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

CREATE TABLE IF NOT EXISTS "Projects" (
    "Id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint       NOT NULL,
    "Name"       varchar(200) NOT NULL,
    "IsActive"   boolean      NOT NULL DEFAULT TRUE,
    "CreatedAt"  timestamp with time zone NOT NULL,
    "UpdatedAt"  timestamp with time zone NULL,
    CONSTRAINT "FK_Projects_Customers_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Projects_CustomerId_Name"
    ON "Projects" ("CustomerId", "Name");

CREATE TABLE IF NOT EXISTS "WorkDayProjects" (
    "Id"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WorkDayId" bigint        NOT NULL,
    "ProjectId" bigint        NOT NULL,
    "Hours"     numeric(6, 2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_WorkDayProjects_WorkDays_WorkDayId"
        FOREIGN KEY ("WorkDayId") REFERENCES "WorkDays" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkDayProjects_Projects_ProjectId"
        FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_WorkDayProjects_ProjectId"
    ON "WorkDayProjects" ("ProjectId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorkDayProjects_WorkDayId_ProjectId"
    ON "WorkDayProjects" ("WorkDayId", "ProjectId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260906182657_AddProjectsAndWorkDayProjects', '10.0.9')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
