-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20261003115507_AddVerifactuSubmissions
-- Where each Verifactu record stands with the Tax Agency (AEAT): waiting, accepted, accepted with errors
-- or rejected. Unlike the records themselves, which are append-only, these rows change as records are sent.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

CREATE TABLE IF NOT EXISTS "VerifactuSubmissions" (
    "Id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "RecordId"      bigint        NOT NULL,
    "Sequence"      bigint        NOT NULL,
    "Status"        varchar(20)   NOT NULL,
    "Attempts"      integer       NOT NULL,
    "LastAttemptAt" timestamp with time zone NULL,
    "NextAttemptAt" timestamp with time zone NOT NULL,
    "AnsweredAt"    timestamp with time zone NULL,
    "Csv"           varchar(50)   NULL,
    "ErrorCode"     varchar(20)   NULL,
    "Message"       varchar(1600) NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "UpdatedAt"     timestamp with time zone NULL,
    "OwnerId"       varchar(255)  NOT NULL,
    CONSTRAINT "PK_VerifactuSubmissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VerifactuSubmissions_VerifactuRecords_RecordId"
        FOREIGN KEY ("RecordId") REFERENCES "VerifactuRecords" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_VerifactuSubmissions_OwnerId"
    ON "VerifactuSubmissions" ("OwnerId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_VerifactuSubmissions_RecordId"
    ON "VerifactuSubmissions" ("RecordId");

CREATE INDEX IF NOT EXISTS "IX_VerifactuSubmissions_Status_NextAttemptAt"
    ON "VerifactuSubmissions" ("Status", "NextAttemptAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261003115507_AddVerifactuSubmissions', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
