-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20261003113445_AddVerifactu
-- Verifactu: the hash-chained record of every invoice issued or cancelled, and the extra data country
-- regimes ask for on each tax (how a 0% VAT is treated).
-- The records are append-only. The application refuses to change or delete them; the trigger below
-- makes the database refuse too, so not even a stray SQL statement can alter the chain.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

ALTER TABLE "Taxes" ADD COLUMN IF NOT EXISTS "ComplianceValues" text NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS "VerifactuRecords" (
    "Id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "Sequence"      bigint       NOT NULL,
    "Kind"          varchar(20)  NOT NULL,
    "InvoiceId"     bigint       NOT NULL,
    "IssuerTaxId"   varchar(9)   NOT NULL,
    "InvoiceNumber" varchar(60)  NOT NULL,
    "IssueDate"     varchar(10)  NOT NULL,
    "InvoiceType"   varchar(2)   NOT NULL,
    "TotalTax"      varchar(20)  NOT NULL,
    "TotalAmount"   varchar(20)  NOT NULL,
    "PreviousHash"  varchar(64)  NOT NULL,
    "GeneratedAt"   varchar(40)  NOT NULL,
    "Hash"          varchar(64)  NOT NULL,
    "Xml"           text         NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "UpdatedAt"     timestamp with time zone NULL,
    "OwnerId"       varchar(255) NOT NULL,
    CONSTRAINT "PK_VerifactuRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VerifactuRecords_Invoices_InvoiceId"
        FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_VerifactuRecords_InvoiceId"
    ON "VerifactuRecords" ("InvoiceId");

CREATE INDEX IF NOT EXISTS "IX_VerifactuRecords_OwnerId"
    ON "VerifactuRecords" ("OwnerId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_VerifactuRecords_OwnerId_Sequence"
    ON "VerifactuRecords" ("OwnerId", "Sequence");

CREATE OR REPLACE FUNCTION verifactu_records_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Verifactu records are append-only: a saved record cannot be changed or deleted';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS verifactu_records_append_only ON "VerifactuRecords";
CREATE TRIGGER verifactu_records_append_only
    BEFORE UPDATE OR DELETE ON "VerifactuRecords"
    FOR EACH ROW EXECUTE FUNCTION verifactu_records_append_only();

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261003113445_AddVerifactu', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
