-- nInvoices :: PostgreSQL migration
-- Mirrors EF migration 20261003084759_AddComplianceSettings
-- Country invoicing regimes (tax compliance): one record per user and country with whether it
-- is turned on, the issuer identity and the country-specific values (JSON). Off by default:
-- no rows means no regime applies.
-- Idempotent: safe to run repeatedly.

\set ON_ERROR_STOP on
\connect ninvoices_db

BEGIN;

CREATE TABLE IF NOT EXISTS "ComplianceSettings" (
    "Id"                  bigint GENERATED BY DEFAULT AS IDENTITY,
    "CountryCode"         varchar(2)   NOT NULL,
    "IsEnabled"           boolean      NOT NULL,
    "LegalName"           varchar(200) NULL,
    "TaxId"               varchar(50)  NULL,
    "Address_Street"      varchar(200) NULL,
    "Address_HouseNumber" varchar(20)  NULL,
    "Address_City"        varchar(100) NULL,
    "Address_ZipCode"     varchar(20)  NULL,
    "Address_State"       varchar(100) NULL,
    "Address_Country"     varchar(100) NULL,
    "Values"              text         NOT NULL,
    "CreatedAt"           timestamp with time zone NOT NULL,
    "UpdatedAt"           timestamp with time zone NULL,
    "OwnerId"             varchar(255) NOT NULL,
    CONSTRAINT "PK_ComplianceSettings" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_ComplianceSettings_OwnerId"
    ON "ComplianceSettings" ("OwnerId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ComplianceSettings_OwnerId_CountryCode"
    ON "ComplianceSettings" ("OwnerId", "CountryCode");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261003084759_AddComplianceSettings', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
