-- Schema of the production database (pg_dump --schema-only --no-owner --no-privileges, no data),
-- taken 2026-10-06 after applying 20261006-0753_align-with-ef-model.sql (API c7169f0). PostgreSqlMigrationScriptsTests restores it, runs
-- docker/migrations-postgres/*.sql on it like deploy.sh, and compares the result with the EF model.
-- Refresh it after a deploy that changes the schema.

--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: verifactu_records_append_only(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.verifactu_records_append_only() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION 'Verifactu records are append-only: a saved record cannot be changed or deleted';
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AccessRequests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AccessRequests" (
    "Id" bigint NOT NULL,
    "Email" text,
    "Name" text,
    "NotifiedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: AccessRequests_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AccessRequests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AccessRequests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ComplianceSettings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ComplianceSettings" (
    "Id" bigint NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "LegalName" text,
    "TaxId" text,
    "Address_Street" text,
    "Address_HouseNumber" text,
    "Address_City" text,
    "Address_ZipCode" text,
    "Address_State" text,
    "Address_Country" text,
    "Values" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL,
    "CertificateNotAfter" timestamp with time zone,
    "CertificateSubject" character varying(500),
    "CertificateThumbprint" character varying(100),
    "ProtectedCertificate" text,
    "ProtectedCertificatePassword" character varying(4000)
);


--
-- Name: ComplianceSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ComplianceSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ComplianceSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Customers" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "FiscalId" text NOT NULL,
    "Address_Street" text NOT NULL,
    "Address_HouseNumber" text NOT NULL,
    "Address_City" text NOT NULL,
    "Address_ZipCode" text NOT NULL,
    "Address_State" text,
    "Address_Country" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "Locale" text NOT NULL,
    "HolidayCountry" character varying(2),
    "Email" text,
    "CcEmails" text,
    "OwnerId" character varying(255) NOT NULL,
    "ComplianceValues" text DEFAULT '{}'::text NOT NULL
);


--
-- Name: Customers_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Customers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Customers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EInvoiceSubmissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."EInvoiceSubmissions" (
    "Id" bigint NOT NULL,
    "InvoiceEInvoiceId" bigint NOT NULL,
    "ChannelId" character varying(50) NOT NULL,
    "Environment" character varying(20) NOT NULL,
    "Reference" character varying(100) NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "RegisteredAt" timestamp with time zone,
    "StatusCode" character varying(20),
    "StatusName" character varying(200),
    "CancellationStatus" character varying(200),
    "CheckedAt" timestamp with time zone,
    "LastError" character varying(1600),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: EInvoiceSubmissions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."EInvoiceSubmissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EInvoiceSubmissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: EmailTemplates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."EmailTemplates" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint,
    "Name" character varying(200) NOT NULL,
    "Subject" text NOT NULL,
    "Body" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: EmailTemplates_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."EmailTemplates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EmailTemplates_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Expenses" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint NOT NULL,
    "InvoiceId" bigint,
    "Date" date NOT NULL,
    "Description" text NOT NULL,
    "Amount" text NOT NULL,
    "Currency" character varying(3) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: Expenses_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Expenses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Expenses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GmailConnections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GmailConnections" (
    "Id" bigint NOT NULL,
    "UserId" character varying(200) NOT NULL,
    "EmailAddress" character varying(320) NOT NULL,
    "EncryptedRefreshToken" character varying(4000) NOT NULL,
    "Scopes" character varying(1000) NOT NULL,
    "ConnectedAt" timestamp with time zone NOT NULL,
    "LastUsedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


--
-- Name: GmailConnections_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."GmailConnections" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GmailConnections_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HolidayCalendars; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."HolidayCalendars" (
    "Id" bigint NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: HolidayCalendars_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."HolidayCalendars" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HolidayCalendars_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HolidayRules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."HolidayRules" (
    "Id" bigint NOT NULL,
    "HolidayCalendarId" bigint NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Kind" character varying(20) NOT NULL,
    "Month" integer,
    "Day" integer,
    "EasterOffset" integer,
    "Weekday" character varying(10),
    "Occurrence" integer,
    "FromYear" integer,
    "ToYear" integer,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: HolidayRules_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."HolidayRules" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HolidayRules_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ImageAssets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ImageAssets" (
    "Id" bigint NOT NULL,
    "Alias" text NOT NULL,
    "FileName" text NOT NULL,
    "ContentType" text NOT NULL,
    "Base64Data" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: ImageAssets_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ImageAssets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ImageAssets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InvoiceEInvoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."InvoiceEInvoices" (
    "Id" bigint NOT NULL,
    "InvoiceId" bigint NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "FormatId" character varying(50) NOT NULL,
    "Content" bytea NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "FileExtension" character varying(10) NOT NULL,
    "Sha256" character varying(64) NOT NULL,
    "GeneratedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: InvoiceEInvoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."InvoiceEInvoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InvoiceEInvoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InvoiceEmails; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."InvoiceEmails" (
    "Id" bigint NOT NULL,
    "InvoiceId" bigint NOT NULL,
    "From" text NOT NULL,
    "To" text NOT NULL,
    "Cc" text,
    "Subject" text NOT NULL,
    "Attachments" text NOT NULL,
    "GmailDraftId" character varying(200) NOT NULL,
    "GmailMessageId" character varying(200) NOT NULL,
    "RfcMessageId" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: InvoiceEmails_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."InvoiceEmails" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InvoiceEmails_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InvoiceSequence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."InvoiceSequence" (
    "Id" bigint NOT NULL,
    "CurrentValue" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL,
    "NumberFormat" character varying(100)
);


--
-- Name: InvoiceSequence_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."InvoiceSequence" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InvoiceSequence_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InvoiceTaxLines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."InvoiceTaxLines" (
    "Id" bigint NOT NULL,
    "InvoiceId" bigint NOT NULL,
    "TaxId" character varying(50) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Rate" numeric(18,4) NOT NULL,
    "BaseAmount" text NOT NULL,
    "BaseCurrency" character varying(3) NOT NULL,
    "TaxAmount" text NOT NULL,
    "TaxCurrency" character varying(3) NOT NULL,
    "Order" integer NOT NULL,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: InvoiceTaxLines_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."InvoiceTaxLines" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InvoiceTaxLines_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InvoiceTemplates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."InvoiceTemplates" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint,
    "InvoiceType" text NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "Format" character varying(20) DEFAULT 'html'::character varying NOT NULL,
    "Version" integer DEFAULT 1 NOT NULL,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: InvoiceTemplates_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."InvoiceTemplates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InvoiceTemplates_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Invoices" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint NOT NULL,
    "InvoiceNumber" character varying(100) NOT NULL,
    "Type" text NOT NULL,
    "Status" text DEFAULT 'Draft'::text NOT NULL,
    "IssueDate" date NOT NULL,
    "DueDate" date,
    "WorkedDays" integer,
    "Year" integer,
    "Month" integer,
    "SubtotalAmount" text NOT NULL,
    "SubtotalCurrency" character varying(3) NOT NULL,
    "TotalExpensesAmount" text NOT NULL,
    "TotalExpensesCurrency" character varying(3) NOT NULL,
    "TotalTaxesAmount" text NOT NULL,
    "TotalTaxesCurrency" character varying(3) NOT NULL,
    "TotalAmount" text NOT NULL,
    "TotalCurrency" character varying(3) NOT NULL,
    "RenderedContent" text,
    "Notes" text,
    "MonthlyReportTemplateId" bigint,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL,
    "RateId" bigint,
    "Hours" numeric(9,2)
);


--
-- Name: Invoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Invoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Invoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MonthlyReportTemplates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MonthlyReportTemplates" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint,
    "Name" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "InvoiceType" integer NOT NULL,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: MonthlyReportTemplates_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."MonthlyReportTemplates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MonthlyReportTemplates_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OAuthStates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."OAuthStates" (
    "Id" bigint NOT NULL,
    "State" character varying(100) NOT NULL,
    "UserId" character varying(200) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


--
-- Name: OAuthStates_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."OAuthStates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OAuthStates_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Projects" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: Projects_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Projects" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Projects_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Rates" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint NOT NULL,
    "Type" text NOT NULL,
    "PriceAmount" text NOT NULL,
    "PriceCurrency" character varying(3) NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL,
    "Name" character varying(100)
);


--
-- Name: Rates_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Rates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Rates_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Taxes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Taxes" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint NOT NULL,
    "TaxId" character varying(50) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "HandlerId" character varying(50) NOT NULL,
    "Rate" numeric(18,4) NOT NULL,
    "ApplicationType" text NOT NULL,
    "AppliedToTaxId" bigint,
    "Order" integer DEFAULT 0 NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL,
    "ComplianceValues" text DEFAULT '{}'::text NOT NULL
);


--
-- Name: Taxes_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Taxes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Taxes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserKeys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserKeys" (
    "Id" uuid NOT NULL,
    "OwnerId" character varying(255) NOT NULL,
    "MasterKeyId" character varying(16) NOT NULL,
    "WrappedKey" bytea NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: VerifactuRecords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."VerifactuRecords" (
    "Id" bigint NOT NULL,
    "Sequence" bigint NOT NULL,
    "Kind" character varying(20) NOT NULL,
    "InvoiceId" bigint NOT NULL,
    "IssuerTaxId" text NOT NULL,
    "InvoiceNumber" character varying(60) NOT NULL,
    "IssueDate" character varying(10) NOT NULL,
    "InvoiceType" character varying(2) NOT NULL,
    "TotalTax" text NOT NULL,
    "TotalAmount" text NOT NULL,
    "PreviousHash" character varying(64) NOT NULL,
    "GeneratedAt" character varying(40) NOT NULL,
    "Hash" character varying(64) NOT NULL,
    "Xml" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: VerifactuRecords_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."VerifactuRecords" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VerifactuRecords_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: VerifactuSubmissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."VerifactuSubmissions" (
    "Id" bigint NOT NULL,
    "RecordId" bigint NOT NULL,
    "Sequence" bigint NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Attempts" integer NOT NULL,
    "LastAttemptAt" timestamp with time zone,
    "NextAttemptAt" timestamp with time zone NOT NULL,
    "AnsweredAt" timestamp with time zone,
    "Csv" character varying(50),
    "ErrorCode" character varying(20),
    "Message" character varying(1600),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: VerifactuSubmissions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."VerifactuSubmissions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VerifactuSubmissions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: WorkDayProjects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."WorkDayProjects" (
    "Id" bigint NOT NULL,
    "WorkDayId" bigint NOT NULL,
    "ProjectId" bigint NOT NULL,
    "Hours" numeric(6,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "OwnerId" character varying(255) NOT NULL
);


--
-- Name: WorkDayProjects_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."WorkDayProjects" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WorkDayProjects_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: WorkDays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."WorkDays" (
    "Id" bigint NOT NULL,
    "CustomerId" bigint NOT NULL,
    "Date" date NOT NULL,
    "DayType" integer NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "HoursWorked" numeric(18,2),
    "OwnerId" character varying(255) NOT NULL,
    "RateId" bigint
);


--
-- Name: WorkDays_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."WorkDays" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WorkDays_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: AccessRequests PK_AccessRequests; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AccessRequests"
    ADD CONSTRAINT "PK_AccessRequests" PRIMARY KEY ("Id");


--
-- Name: ComplianceSettings PK_ComplianceSettings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ComplianceSettings"
    ADD CONSTRAINT "PK_ComplianceSettings" PRIMARY KEY ("Id");


--
-- Name: Customers PK_Customers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");


--
-- Name: EInvoiceSubmissions PK_EInvoiceSubmissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EInvoiceSubmissions"
    ADD CONSTRAINT "PK_EInvoiceSubmissions" PRIMARY KEY ("Id");


--
-- Name: EmailTemplates PK_EmailTemplates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EmailTemplates"
    ADD CONSTRAINT "PK_EmailTemplates" PRIMARY KEY ("Id");


--
-- Name: Expenses PK_Expenses; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Expenses"
    ADD CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id");


--
-- Name: GmailConnections PK_GmailConnections; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GmailConnections"
    ADD CONSTRAINT "PK_GmailConnections" PRIMARY KEY ("Id");


--
-- Name: HolidayCalendars PK_HolidayCalendars; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."HolidayCalendars"
    ADD CONSTRAINT "PK_HolidayCalendars" PRIMARY KEY ("Id");


--
-- Name: HolidayRules PK_HolidayRules; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."HolidayRules"
    ADD CONSTRAINT "PK_HolidayRules" PRIMARY KEY ("Id");


--
-- Name: ImageAssets PK_ImageAssets; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ImageAssets"
    ADD CONSTRAINT "PK_ImageAssets" PRIMARY KEY ("Id");


--
-- Name: InvoiceEInvoices PK_InvoiceEInvoices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceEInvoices"
    ADD CONSTRAINT "PK_InvoiceEInvoices" PRIMARY KEY ("Id");


--
-- Name: InvoiceEmails PK_InvoiceEmails; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceEmails"
    ADD CONSTRAINT "PK_InvoiceEmails" PRIMARY KEY ("Id");


--
-- Name: InvoiceSequence PK_InvoiceSequence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceSequence"
    ADD CONSTRAINT "PK_InvoiceSequence" PRIMARY KEY ("Id");


--
-- Name: InvoiceTaxLines PK_InvoiceTaxLines; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceTaxLines"
    ADD CONSTRAINT "PK_InvoiceTaxLines" PRIMARY KEY ("Id");


--
-- Name: InvoiceTemplates PK_InvoiceTemplates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceTemplates"
    ADD CONSTRAINT "PK_InvoiceTemplates" PRIMARY KEY ("Id");


--
-- Name: Invoices PK_Invoices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id");


--
-- Name: MonthlyReportTemplates PK_MonthlyReportTemplates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MonthlyReportTemplates"
    ADD CONSTRAINT "PK_MonthlyReportTemplates" PRIMARY KEY ("Id");


--
-- Name: OAuthStates PK_OAuthStates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OAuthStates"
    ADD CONSTRAINT "PK_OAuthStates" PRIMARY KEY ("Id");


--
-- Name: Projects PK_Projects; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Projects"
    ADD CONSTRAINT "PK_Projects" PRIMARY KEY ("Id");


--
-- Name: Rates PK_Rates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rates"
    ADD CONSTRAINT "PK_Rates" PRIMARY KEY ("Id");


--
-- Name: Taxes PK_Taxes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Taxes"
    ADD CONSTRAINT "PK_Taxes" PRIMARY KEY ("Id");


--
-- Name: UserKeys PK_UserKeys; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserKeys"
    ADD CONSTRAINT "PK_UserKeys" PRIMARY KEY ("Id");


--
-- Name: VerifactuRecords PK_VerifactuRecords; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VerifactuRecords"
    ADD CONSTRAINT "PK_VerifactuRecords" PRIMARY KEY ("Id");


--
-- Name: VerifactuSubmissions PK_VerifactuSubmissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VerifactuSubmissions"
    ADD CONSTRAINT "PK_VerifactuSubmissions" PRIMARY KEY ("Id");


--
-- Name: WorkDayProjects PK_WorkDayProjects; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."WorkDayProjects"
    ADD CONSTRAINT "PK_WorkDayProjects" PRIMARY KEY ("Id");


--
-- Name: WorkDays PK_WorkDays; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."WorkDays"
    ADD CONSTRAINT "PK_WorkDays" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory __EFMigrationsHistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "__EFMigrationsHistory_pkey" PRIMARY KEY ("MigrationId");


--
-- Name: IX_AccessRequests_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_AccessRequests_OwnerId" ON public."AccessRequests" USING btree ("OwnerId");


--
-- Name: IX_ComplianceSettings_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ComplianceSettings_OwnerId" ON public."ComplianceSettings" USING btree ("OwnerId");


--
-- Name: IX_ComplianceSettings_OwnerId_CountryCode; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ComplianceSettings_OwnerId_CountryCode" ON public."ComplianceSettings" USING btree ("OwnerId", "CountryCode");


--
-- Name: IX_Customers_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Customers_OwnerId" ON public."Customers" USING btree ("OwnerId");


--
-- Name: IX_EInvoiceSubmissions_InvoiceEInvoiceId_ChannelId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_EInvoiceSubmissions_InvoiceEInvoiceId_ChannelId" ON public."EInvoiceSubmissions" USING btree ("InvoiceEInvoiceId", "ChannelId");


--
-- Name: IX_EInvoiceSubmissions_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_EInvoiceSubmissions_OwnerId" ON public."EInvoiceSubmissions" USING btree ("OwnerId");


--
-- Name: IX_EmailTemplates_CustomerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_EmailTemplates_CustomerId" ON public."EmailTemplates" USING btree ("CustomerId");


--
-- Name: IX_EmailTemplates_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_EmailTemplates_OwnerId" ON public."EmailTemplates" USING btree ("OwnerId");


--
-- Name: IX_Expenses_CustomerId_Date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Expenses_CustomerId_Date" ON public."Expenses" USING btree ("CustomerId", "Date");


--
-- Name: IX_Expenses_InvoiceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Expenses_InvoiceId" ON public."Expenses" USING btree ("InvoiceId");


--
-- Name: IX_Expenses_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Expenses_OwnerId" ON public."Expenses" USING btree ("OwnerId");


--
-- Name: IX_GmailConnections_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_GmailConnections_UserId" ON public."GmailConnections" USING btree ("UserId");


--
-- Name: IX_HolidayCalendars_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_HolidayCalendars_OwnerId" ON public."HolidayCalendars" USING btree ("OwnerId");


--
-- Name: IX_HolidayCalendars_OwnerId_CountryCode; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_HolidayCalendars_OwnerId_CountryCode" ON public."HolidayCalendars" USING btree ("OwnerId", "CountryCode");


--
-- Name: IX_HolidayRules_HolidayCalendarId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_HolidayRules_HolidayCalendarId" ON public."HolidayRules" USING btree ("HolidayCalendarId");


--
-- Name: IX_HolidayRules_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_HolidayRules_OwnerId" ON public."HolidayRules" USING btree ("OwnerId");


--
-- Name: IX_ImageAssets_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ImageAssets_OwnerId" ON public."ImageAssets" USING btree ("OwnerId");


--
-- Name: IX_ImageAssets_OwnerId_Alias; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ImageAssets_OwnerId_Alias" ON public."ImageAssets" USING btree ("OwnerId", "Alias");


--
-- Name: IX_InvoiceEInvoices_InvoiceId_FormatId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_InvoiceEInvoices_InvoiceId_FormatId" ON public."InvoiceEInvoices" USING btree ("InvoiceId", "FormatId");


--
-- Name: IX_InvoiceEInvoices_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvoiceEInvoices_OwnerId" ON public."InvoiceEInvoices" USING btree ("OwnerId");


--
-- Name: IX_InvoiceEmails_InvoiceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvoiceEmails_InvoiceId" ON public."InvoiceEmails" USING btree ("InvoiceId");


--
-- Name: IX_InvoiceEmails_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvoiceEmails_OwnerId" ON public."InvoiceEmails" USING btree ("OwnerId");


--
-- Name: IX_InvoiceSequence_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_InvoiceSequence_OwnerId" ON public."InvoiceSequence" USING btree ("OwnerId");


--
-- Name: IX_InvoiceTaxLines_InvoiceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvoiceTaxLines_InvoiceId" ON public."InvoiceTaxLines" USING btree ("InvoiceId");


--
-- Name: IX_InvoiceTaxLines_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvoiceTaxLines_OwnerId" ON public."InvoiceTaxLines" USING btree ("OwnerId");


--
-- Name: IX_InvoiceTemplates_CustomerId_InvoiceType_IsActive; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_InvoiceTemplates_CustomerId_InvoiceType_IsActive" ON public."InvoiceTemplates" USING btree ("CustomerId", "InvoiceType", "IsActive") WHERE "IsActive";


--
-- Name: IX_InvoiceTemplates_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_InvoiceTemplates_OwnerId" ON public."InvoiceTemplates" USING btree ("OwnerId");


--
-- Name: IX_InvoiceTemplates_Shared_OwnerId_InvoiceType; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_InvoiceTemplates_Shared_OwnerId_InvoiceType" ON public."InvoiceTemplates" USING btree ("OwnerId", "InvoiceType") WHERE ("IsActive" AND ("CustomerId" IS NULL));


--
-- Name: IX_Invoices_CustomerId_Year_Month; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Invoices_CustomerId_Year_Month" ON public."Invoices" USING btree ("CustomerId", "Year", "Month");


--
-- Name: IX_Invoices_IssueDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Invoices_IssueDate" ON public."Invoices" USING btree ("IssueDate");


--
-- Name: IX_Invoices_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Invoices_OwnerId" ON public."Invoices" USING btree ("OwnerId");


--
-- Name: IX_Invoices_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Invoices_Status" ON public."Invoices" USING btree ("Status");


--
-- Name: IX_MonthlyReportTemplates_CustomerId_InvoiceType_IsActive; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MonthlyReportTemplates_CustomerId_InvoiceType_IsActive" ON public."MonthlyReportTemplates" USING btree ("CustomerId", "InvoiceType", "IsActive");


--
-- Name: IX_MonthlyReportTemplates_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MonthlyReportTemplates_OwnerId" ON public."MonthlyReportTemplates" USING btree ("OwnerId");


--
-- Name: IX_OAuthStates_State; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_OAuthStates_State" ON public."OAuthStates" USING btree ("State");


--
-- Name: IX_Projects_CustomerId_Name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Projects_CustomerId_Name" ON public."Projects" USING btree ("CustomerId", "Name");


--
-- Name: IX_Projects_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Projects_OwnerId" ON public."Projects" USING btree ("OwnerId");


--
-- Name: IX_Rates_CustomerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Rates_CustomerId" ON public."Rates" USING btree ("CustomerId");


--
-- Name: IX_Rates_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Rates_OwnerId" ON public."Rates" USING btree ("OwnerId");


--
-- Name: IX_Taxes_AppliedToTaxId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Taxes_AppliedToTaxId" ON public."Taxes" USING btree ("AppliedToTaxId");


--
-- Name: IX_Taxes_CustomerId_TaxId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Taxes_CustomerId_TaxId" ON public."Taxes" USING btree ("CustomerId", "TaxId");


--
-- Name: IX_Taxes_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Taxes_OwnerId" ON public."Taxes" USING btree ("OwnerId");


--
-- Name: IX_UserKeys_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_UserKeys_OwnerId" ON public."UserKeys" USING btree ("OwnerId");


--
-- Name: IX_VerifactuRecords_InvoiceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VerifactuRecords_InvoiceId" ON public."VerifactuRecords" USING btree ("InvoiceId");


--
-- Name: IX_VerifactuRecords_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VerifactuRecords_OwnerId" ON public."VerifactuRecords" USING btree ("OwnerId");


--
-- Name: IX_VerifactuRecords_OwnerId_Sequence; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_VerifactuRecords_OwnerId_Sequence" ON public."VerifactuRecords" USING btree ("OwnerId", "Sequence");


--
-- Name: IX_VerifactuSubmissions_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VerifactuSubmissions_OwnerId" ON public."VerifactuSubmissions" USING btree ("OwnerId");


--
-- Name: IX_VerifactuSubmissions_RecordId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_VerifactuSubmissions_RecordId" ON public."VerifactuSubmissions" USING btree ("RecordId");


--
-- Name: IX_VerifactuSubmissions_Status_NextAttemptAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_VerifactuSubmissions_Status_NextAttemptAt" ON public."VerifactuSubmissions" USING btree ("Status", "NextAttemptAt");


--
-- Name: IX_WorkDayProjects_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_WorkDayProjects_OwnerId" ON public."WorkDayProjects" USING btree ("OwnerId");


--
-- Name: IX_WorkDayProjects_ProjectId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_WorkDayProjects_ProjectId" ON public."WorkDayProjects" USING btree ("ProjectId");


--
-- Name: IX_WorkDayProjects_WorkDayId_ProjectId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_WorkDayProjects_WorkDayId_ProjectId" ON public."WorkDayProjects" USING btree ("WorkDayId", "ProjectId");


--
-- Name: IX_WorkDays_CustomerId_Date; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_WorkDays_CustomerId_Date" ON public."WorkDays" USING btree ("CustomerId", "Date");


--
-- Name: IX_WorkDays_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_WorkDays_OwnerId" ON public."WorkDays" USING btree ("OwnerId");


--
-- Name: VerifactuRecords verifactu_records_append_only; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER verifactu_records_append_only BEFORE DELETE OR UPDATE ON public."VerifactuRecords" FOR EACH ROW EXECUTE FUNCTION public.verifactu_records_append_only();


--
-- Name: EInvoiceSubmissions FK_EInvoiceSubmissions_InvoiceEInvoices_InvoiceEInvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EInvoiceSubmissions"
    ADD CONSTRAINT "FK_EInvoiceSubmissions_InvoiceEInvoices_InvoiceEInvoiceId" FOREIGN KEY ("InvoiceEInvoiceId") REFERENCES public."InvoiceEInvoices"("Id") ON DELETE RESTRICT;


--
-- Name: EmailTemplates FK_EmailTemplates_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EmailTemplates"
    ADD CONSTRAINT "FK_EmailTemplates_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Expenses FK_Expenses_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Expenses"
    ADD CONSTRAINT "FK_Expenses_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Expenses FK_Expenses_Invoices_InvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Expenses"
    ADD CONSTRAINT "FK_Expenses_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES public."Invoices"("Id") ON DELETE SET NULL;


--
-- Name: HolidayRules FK_HolidayRules_HolidayCalendars_HolidayCalendarId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."HolidayRules"
    ADD CONSTRAINT "FK_HolidayRules_HolidayCalendars_HolidayCalendarId" FOREIGN KEY ("HolidayCalendarId") REFERENCES public."HolidayCalendars"("Id") ON DELETE CASCADE;


--
-- Name: InvoiceEInvoices FK_InvoiceEInvoices_Invoices_InvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceEInvoices"
    ADD CONSTRAINT "FK_InvoiceEInvoices_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES public."Invoices"("Id") ON DELETE CASCADE;


--
-- Name: InvoiceEmails FK_InvoiceEmails_Invoices_InvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceEmails"
    ADD CONSTRAINT "FK_InvoiceEmails_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES public."Invoices"("Id") ON DELETE CASCADE;


--
-- Name: InvoiceTaxLines FK_InvoiceTaxLines_Invoices_InvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceTaxLines"
    ADD CONSTRAINT "FK_InvoiceTaxLines_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES public."Invoices"("Id") ON DELETE CASCADE;


--
-- Name: InvoiceTemplates FK_InvoiceTemplates_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."InvoiceTemplates"
    ADD CONSTRAINT "FK_InvoiceTemplates_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Invoices FK_Invoices_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "FK_Invoices_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE RESTRICT;


--
-- Name: MonthlyReportTemplates FK_MonthlyReportTemplates_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MonthlyReportTemplates"
    ADD CONSTRAINT "FK_MonthlyReportTemplates_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Projects FK_Projects_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Projects"
    ADD CONSTRAINT "FK_Projects_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Rates FK_Rates_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rates"
    ADD CONSTRAINT "FK_Rates_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Taxes FK_Taxes_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Taxes"
    ADD CONSTRAINT "FK_Taxes_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- Name: Taxes FK_Taxes_Taxes_AppliedToTaxId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Taxes"
    ADD CONSTRAINT "FK_Taxes_Taxes_AppliedToTaxId" FOREIGN KEY ("AppliedToTaxId") REFERENCES public."Taxes"("Id") ON DELETE RESTRICT;


--
-- Name: VerifactuRecords FK_VerifactuRecords_Invoices_InvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VerifactuRecords"
    ADD CONSTRAINT "FK_VerifactuRecords_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES public."Invoices"("Id") ON DELETE RESTRICT;


--
-- Name: VerifactuSubmissions FK_VerifactuSubmissions_VerifactuRecords_RecordId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."VerifactuSubmissions"
    ADD CONSTRAINT "FK_VerifactuSubmissions_VerifactuRecords_RecordId" FOREIGN KEY ("RecordId") REFERENCES public."VerifactuRecords"("Id") ON DELETE RESTRICT;


--
-- Name: WorkDayProjects FK_WorkDayProjects_Projects_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."WorkDayProjects"
    ADD CONSTRAINT "FK_WorkDayProjects_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public."Projects"("Id") ON DELETE RESTRICT;


--
-- Name: WorkDayProjects FK_WorkDayProjects_WorkDays_WorkDayId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."WorkDayProjects"
    ADD CONSTRAINT "FK_WorkDayProjects_WorkDays_WorkDayId" FOREIGN KEY ("WorkDayId") REFERENCES public."WorkDays"("Id") ON DELETE CASCADE;


--
-- Name: WorkDays FK_WorkDays_Customers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."WorkDays"
    ADD CONSTRAINT "FK_WorkDays_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


