// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nInvoices.Infrastructure.Data;

#nullable disable

namespace nInvoices.Infrastructure.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("nInvoices.Core.Entities.AccessRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "AccessRequest.Email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "AccessRequest.Name");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("AccessRequests", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.ComplianceSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CertificateNotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CertificateSubject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CertificateThumbprint")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.LegalName");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProtectedCertificate")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedCertificatePassword")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("TaxId")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.TaxId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "CountryCode")
                        .IsUnique();

                    b.ToTable("ComplianceSettings", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CcEmails")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.CcEmails");

                    b.Property<string>("ComplianceValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Email");

                    b.Property<string>("FiscalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.FiscalId");

                    b.Property<string>("HolidayCountry")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.EInvoiceSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CancellationStatus")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("InvoiceEInvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("InvoiceEInvoiceId", "ChannelId")
                        .IsUnique();

                    b.ToTable("EInvoiceSubmissions", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.EmailTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "EmailTemplate.Body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "EmailTemplate.Subject");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "Expense.Description");

                    b.Property<long?>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CustomerId", "Date");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.GmailConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GmailConnections", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.HolidayCalendar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "CountryCode")
                        .IsUnique();

                    b.ToTable("HolidayCalendars", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.HolidayRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Day")
                        .HasColumnType("integer");

                    b.Property<int?>("EasterOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("FromYear")
                        .HasColumnType("integer");

                    b.Property<long>("HolidayCalendarId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Occurrence")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ToYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Weekday")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("HolidayCalendarId");

                    b.HasIndex("OwnerId");

                    b.ToTable("HolidayRules", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.ImageAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Base64Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Alias")
                        .IsUnique();

                    b.ToTable("ImageAssets");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Hours")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int?>("Month")
                        .HasColumnType("integer");

                    b.Property<long?>("MonthlyReportTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "Invoice.Notes");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("RateId")
                        .HasColumnType("bigint");

                    b.Property<string>("RenderedContent")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "Invoice.RenderedContent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkedDays")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IssueDate");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "Year", "Month");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceEInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceEInvoice.Content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FormatId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("InvoiceId", "FormatId")
                        .IsUnique();

                    b.ToTable("InvoiceEInvoices", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceEmail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceEmail.Attachments");

                    b.Property<string>("Cc")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceEmail.Cc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceEmail.From");

                    b.Property<string>("GmailDraftId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GmailMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RfcMessageId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceEmail.Subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceEmail.To");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OwnerId");

                    b.ToTable("InvoiceEmails", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceSequence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<string>("NumberFormat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("InvoiceSequence", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceTaxLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BaseAmount", "nInvoices.Core.Entities.InvoiceTaxLine.BaseAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BaseAmount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceTaxLine.BaseAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("BaseCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TaxAmount", "nInvoices.Core.Entities.InvoiceTaxLine.TaxAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TaxAmount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceTaxLine.TaxAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OwnerId");

                    b.ToTable("InvoiceTaxLines", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "InvoiceTemplate.Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("html");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "InvoiceType")
                        .IsUnique()
                        .HasDatabaseName("IX_InvoiceTemplates_Shared_OwnerId_InvoiceType")
                        .HasFilter("\"IsActive\" AND \"CustomerId\" IS NULL");

                    b.HasIndex("CustomerId", "InvoiceType", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\"");

                    b.ToTable("InvoiceTemplates", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.MonthlyReportTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "MonthlyReportTemplate.Content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CustomerId", "InvoiceType", "IsActive");

                    b.ToTable("MonthlyReportTemplates", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.OAuthState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("OAuthStates", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Rate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Rates", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Tax", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("AppliedToTaxId")
                        .HasColumnType("bigint");

                    b.Property<string>("ComplianceValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HandlerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppliedToTaxId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CustomerId", "TaxId")
                        .IsUnique();

                    b.ToTable("Taxes", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.VerifactuRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IssuerTaxId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "VerifactuRecord.IssuerTaxId");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "VerifactuRecord.TotalAmount");

                    b.Property<string>("TotalTax")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "VerifactuRecord.TotalTax");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "VerifactuRecord.Xml");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Sequence")
                        .IsUnique();

                    b.ToTable("VerifactuRecords", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.VerifactuSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Csv")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RecordId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("VerifactuSubmissions", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.WorkDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HoursWorked")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasAnnotation("nInvoices:EncryptionPurpose", "WorkDay.Notes");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("RateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("CustomerId", "Date")
                        .IsUnique();

                    b.ToTable("WorkDays", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.WorkDayProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Hours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WorkDayId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkDayId", "ProjectId")
                        .IsUnique();

                    b.ToTable("WorkDayProjects", (string)null);
                });

            modelBuilder.Entity("nInvoices.Infrastructure.Encryption.UserKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MasterKeyId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("UserKeys", (string)null);
                });

            modelBuilder.Entity("nInvoices.Core.Entities.ComplianceSettings", b =>
                {
                    b.OwnsOne("nInvoices.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<long>("ComplianceSettingsId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.Address.City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.Address.Country");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.Address.HouseNumber");

                            b1.Property<string>("State")
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.Address.State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.Address.Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "ComplianceSettings.Address.ZipCode");

                            b1.HasKey("ComplianceSettingsId");

                            b1.ToTable("ComplianceSettings");

                            b1.WithOwner()
                                .HasForeignKey("ComplianceSettingsId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Customer", b =>
                {
                    b.OwnsOne("nInvoices.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<long>("CustomerId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Address.City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Address.Country");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Address.HouseNumber");

                            b1.Property<string>("State")
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Address.State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Address.Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Customer.Address.ZipCode");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("nInvoices.Core.Entities.EInvoiceSubmission", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.InvoiceEInvoice", "EInvoice")
                        .WithMany()
                        .HasForeignKey("InvoiceEInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EInvoice");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.EmailTemplate", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Expense", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nInvoices.Core.Entities.Invoice", "Invoice")
                        .WithMany("Expenses")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("nInvoices.Core.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<long>("ExpenseId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Amount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Expense.Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.HolidayRule", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.HolidayCalendar", "HolidayCalendar")
                        .WithMany("Rules")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolidayCalendar");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Invoice", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("nInvoices.Core.ValueObjects.Money", "Subtotal", b1 =>
                        {
                            b1.Property<long>("InvoiceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SubtotalAmount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Invoice.Subtotal");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("SubtotalCurrency");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("nInvoices.Core.ValueObjects.Money", "Total", b1 =>
                        {
                            b1.Property<long>("InvoiceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TotalAmount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Invoice.Total");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalCurrency");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("nInvoices.Core.ValueObjects.Money", "TotalExpenses", b1 =>
                        {
                            b1.Property<long>("InvoiceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TotalExpensesAmount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Invoice.TotalExpenses");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalExpensesCurrency");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("nInvoices.Core.ValueObjects.Money", "TotalTaxes", b1 =>
                        {
                            b1.Property<long>("InvoiceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TotalTaxesAmount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Invoice.TotalTaxes");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalTaxesCurrency");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.OwnsOne("nInvoices.Core.ValueObjects.InvoiceNumber", "Number", b1 =>
                        {
                            b1.Property<long>("InvoiceId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("InvoiceNumber");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("Number")
                        .IsRequired();

                    b.Navigation("Subtotal")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();

                    b.Navigation("TotalExpenses")
                        .IsRequired();

                    b.Navigation("TotalTaxes")
                        .IsRequired();
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceEInvoice", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceEmail", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceTaxLine", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Invoice", "Invoice")
                        .WithMany("TaxLines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.InvoiceTemplate", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany("Templates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.MonthlyReportTemplate", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Project", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Rate", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany("Rates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("nInvoices.Core.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<long>("RateId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PriceAmount")
                                .HasAnnotation("nInvoices:EncryptionPurpose", "Rate.Price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("RateId");

                            b1.ToTable("Rates");

                            b1.WithOwner()
                                .HasForeignKey("RateId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Tax", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Tax", "AppliedToTax")
                        .WithMany()
                        .HasForeignKey("AppliedToTaxId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany("Taxes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedToTax");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.VerifactuRecord", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.VerifactuSubmission", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.VerifactuRecord", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.WorkDay", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.WorkDayProject", b =>
                {
                    b.HasOne("nInvoices.Core.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nInvoices.Core.Entities.WorkDay", "WorkDay")
                        .WithMany("Projects")
                        .HasForeignKey("WorkDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Customer", b =>
                {
                    b.Navigation("EmailTemplates");

                    b.Navigation("Invoices");

                    b.Navigation("Projects");

                    b.Navigation("Rates");

                    b.Navigation("Taxes");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.HolidayCalendar", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.Invoice", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("TaxLines");
                });

            modelBuilder.Entity("nInvoices.Core.Entities.WorkDay", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
